name: web
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: ironman <email@example.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  core:
    path: ../core
  angular: ^5.3.1
  angular_router: ^2.0.0-alpha+19
  key_value_store_web: ^1.0.0
  pwa: ^0.2.0
  firebase_dart_ui: ^0.1.1
  angular_components: ^0.13.0+1
  angular_quill: ^0.1.2
  image: ^2.1.4
  yabwe: ^0.0.2
  dialog: ^0.7.0


dev_dependencies:
  build_runner: ^1.6.6
  build_web_compilers: ^2.2.3
  angular_test: ^2.3.0
  build_test: ^0.10.8
  sass_builder: ^2.1.3
  test: ^1.3.0
  
